# Generated by Django 5.2.10 on 2026-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
